version: '3.7'
services:
  web:
    build: .
    restart: unless-stopped
    environment:
      - 'NODE_ENV=production'
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8080}:3000"
      - "${HOST_PORT:-6379}:6379"
    depends_on:
        redis:
            condition: service_healthy
    links:
        - redis
  redis:
      image: redis:6.2.5-alpine
      healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 1s
          timeout: 2s
          retries: 10

