
CREATE TABLE GENERAL.COMMUNITY_LOCATIONS (
	ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DESCRIPTION NVARCHAR2(500),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT SELECT ON "GENERAL"."COMMUNITY_LOCATIONS" TO "CONSTELLATION_HEALTH";
GRANT SELECT ON "GENERAL"."COMMUNITY_LOCATIONS" TO "HSS_BACKEND";


INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Beaver Creek');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Burwash Landing');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Carcross');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Carmacks');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Dawson City');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Destruction Bay');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Faro');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Haines Junction');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES('Ibex Valley');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Marsh Lake');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Mayo');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Mount Lorne');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Old Crow');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Pelly Crossing');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Ross River');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Tagish');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Teslin');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Watson Lake');
INSERT INTO GENERAL.COMMUNITY_LOCATIONS (DESCRIPTION) VALUES( 'Whitehorse');

ALTER TABLE CONSTELLATION_HEALTH.CONSTELLATION_HEALTH ADD COMMUNITY_LOCATED NVARCHAR2(500);
ALTER TABLE CONSTELLATION_HEALTH.CONSTELLATION_HEALTH_REV ADD COMMUNITY_LOCATED NVARCHAR2(500);
ALTER TABLE CONSTELLATION_HEALTH.CONSTELLATION_HEALTH MODIFY POSTAL_CODE NVARCHAR2(255) NULL;


INSERT INTO MIDWIFERY.MIDWIFERY_BIRTH_LOCATIONS VALUES (4, 'hospital_2', 'I''d prefer to give birth at a hospital.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO MIDWIFERY.MIDWIFERY_BIRTH_LOCATIONS VALUES (5, 'out_hospital', 'I''m considering an out of hospital birth.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO MIDWIFERY.MIDWIFERY_GROUPS_COMMUNITIES VALUES (11, 'mental_wellness_2', 'Person with mental wellness concerns', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO MIDWIFERY.MIDWIFERY_GROUPS_COMMUNITIES VALUES (12, 'substance_concerns', 'Person with substance use concerns', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


Insert into GENERAL.PERMISSION_DATA (ID,PERMISSION_NAME,PERMISSION_DESC,PERMISSION_CATEGORY) values (18,'dental_logs','Dental Logs','Dental');

Insert into GENERAL.ROLES_DATA (ID,ROLE_NAME) values (9,'Dental Logs');

Insert into GENERAL.ROLE_PERMISSIONS (ID,ROLE_ID,PERMISSION_ID) values (38,9,18);
Insert into GENERAL.ROLE_PERMISSIONS (ID,ROLE_ID,PERMISSION_ID) values (39,9,13);

INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (8, 'View Submission Details');
INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (9, 'Download Attachment');
INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (10, 'Insert Attachment');
INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (11, 'Delete Attachment');
INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (12, 'Insert Internal Field');
INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (13, 'Update Internal Field');
INSERT INTO GENERAL.ACTION_TYPES(ID, DESCRIPTION) VALUES (14, 'Insert Comment');

ALTER TABLE "GENERAL"."ACTION_LOGS" ADD ( FIELD1 NUMBER VISIBLE );

Insert into GENERAL.CONFIG (ID,TYPE,NAME,VAL_STR1,VAL_STR2,VAL_STR3,VAL_INT1,VAL_INT2,VAL_INT3,VAL_DATE1,VAL_DATE2,VAL_DATE3) values (32,'STATUS_CHART_COLOR','DENTAL','#dd3e22','>51','DENTAL_CHART_COLOR',4,4,null,null,null,null);
Insert into GENERAL.CONFIG (ID,TYPE,NAME,VAL_STR1,VAL_STR2,VAL_STR3,VAL_INT1,VAL_INT2,VAL_INT3,VAL_DATE1,VAL_DATE2,VAL_DATE3) values (33,'STATUS_CHART_COLOR','DENTAL','#a24bd1',null,'DENTAL_CHART_COLOR',5,null,null,null,null,null);
Insert into GENERAL.CONFIG (ID,TYPE,NAME,VAL_STR1,VAL_STR2,VAL_STR3,VAL_INT1,VAL_INT2,VAL_INT3,VAL_DATE1,VAL_DATE2,VAL_DATE3) values (34,'STATUS_CHART_COLOR','DENTAL','#64dded',null,'DENTAL_CHART_COLOR',6,null,null,null,null,null);