version: "3.8"
services:
    node_hss_backend:
        build: 
            context: "./"
            dockerfile: Dockerfile
        volumes:
            - .:/app/
            - /app/node_modules]
            - "./:/usr/src/app"
            - "./.env:/.env"
        environment:
            NODE_ENV: production
        ports:
            - 8080:8080
            - 3000:3000
            - 6379:6379

