name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the project Docker Redis image
      run: docker build ./redis --file Dockerfile --tag hss-redis-db:$(date +%s)
